### ISSUE TITLE
How to run this successfully?

### ISSUE THREAD

**Issue by achyuth4** [00nx/exodus-decryptor#1]
Hey v4ms,

Could you please help in running your program "exodus-decryptor" step-by-step?

I really can't understand where to select the path or seco file and exodus path and all. Please kindly write a understandable tutorial on how to use? Please understand my request and reply me 

Thank you 👍

**Comment by 00nx** [comment]
theres a fuction which fetches the exodus dir and looks for seed file automatically if you have it installed

```js

function locateExodus() {
    const ExodusPath = path.join(process.env.appdata, "exodus", "exodus.wallet")
    const seedPath = path.join(ExodusPath, "seed.seco")
    if (fs.existsSync(seedPath)) {

        return {
            "exodus": true,
            "path": seedPath,
            "passwordRequired": !fs.existsSync(path.join(ExodusPath, "passphrase.json"))
        }

    }
    return {
        "exodus": false
    }

}
const ExodusPath = path.join(process.env.appdata, "exodus", "exodus.wallet")
```

[ it only works in windows by the way ]
